
project_id = "sdwuhuuyyrwzwyqdtdkb"

[api]
enabled = true
port = 8000
schemas = ["public", "storage", "auth"]

[db]
port = 5432
shadow_port = 54320

[studio]
port = 8001

[[db.remote_schemas]]
name = "supabase_functions"
equals_schemas = ["supabase_functions"]

[functions]
enabled = true
port = 9000
hook_port = 9001

[realtime]
enabled = false

[inbucket]
enabled = false

[storage]
enabled = false
file_size_limit_bytes = 52428800 # 50 MiB
