export const phrases: string[] = [
`I feel like a melting candle`,
`I feel like a skipped song`,
`I feel like a cracked phone screen`,
`I feel like a forgotten birthday`,
`I feel like a goldfish in traffic`,
`I feel like a caffeine crash`,
`I feel like a sunbeam on a cold day`,
`I feel like a misplaced comma`,
`I feel like a half-baked cookie`,
`I feel like a last-minute miracle`,
`I want to dance like a leaf in the wind`,
`I want to vanish like fog`,
`I want to be spellbound`,
`I want to be held by silence`,
`I want to feel infinite`,
`I want to drift like a paper boat`,
`I want to be unraveled`,
`I want to be a thunderclap`,
`I want to scream into the void`,
`I want to laugh like a kid in summer`,
`I feel like a vending machine with no snacks`,
`I feel like an accidental text`,
`I feel like a dusty record`,
`I feel like a wrong turn`,
`I feel like a deflated balloon`,
`I feel like static on the radio`,
`I feel like a missing puzzle piece`,
`I feel like a snowman in July`,
`I feel like an unplugged lamp`,
`I feel like a squirrel in a rave`,
`I want to chase the horizon`,
`I want to be a firework`,
`I want to get lost in a story`,
`I want to hug the moon`,
`I want to feel like magic`,
`I want to sparkle like spilled glitter`,
`I want to be a mystery`,
`I want to cry over beauty`,
`I want to run with no destination`,
`I want to be as still as a pond`,
`I feel like a soggy sandwich`,
`I feel like a rejected emoji`,
`I feel like a haunted playlist`,
`I feel like lukewarm tea`,
`I feel like a benched player`,
`I feel like a sleepy volcano`,
`I feel like a page with no words`,
`I feel like a dream someone forgot`,
`I feel like an uncharged battery`,
`I feel like a coat in summer`,
`I want to be awestruck`,
`I want to glow in the dark`,
`I want to shiver from joy`,
`I want to be the twist in a plot`,
`I want to hum like neon`,
`I want to be weightless`,
`I want to be a surprise`,
`I want to be swept away`,
`I want to unravel something deep`,
`I want to see the world blink`,
`I feel like a lost balloon`,
`I feel like elevator music`,
`I feel like a frozen waffle`,
`I feel like a ghost in a crowd`,
`I feel like a rerun`,
`I feel like the end credits`,
`I feel like background noise`,
`I feel like a scribbled note`,
`I feel like an inside joke no one gets`,
`I feel like a paused song`,
`I want to be moved`,
`I want to burn bright`,
`I want to whisper to the stars`,
`I want to disappear into art`,
`I want to remember everything`,
`I want to be a storm`,
`I want to be the punchline`,
`I want to be hypnotized`,
`I want to feel brand new`,
`I want to be thunderous`,
`I feel like a typo in a love letter`,
`I feel like the last slice no one eats`,
`I feel like a traffic jam at midnight`,
`I feel like a stuck zipper`,
`I feel like an expired coupon`,
`I feel like a forgotten password`,
`I feel like background buffering`,
`I feel like a voicemail no one hears`,
`I feel like a snow day with no snow`,
`I feel like the smell of burnt toast`,
`I want to time travel through music`,
`I want to dream in color`,
`I want to be startled by joy`,
`I want to swim in nostalgia`,
`I want to be a question mark`,
`I want to echo`,
`I want to be the cliffhanger`,
`I want to taste tomorrow`,
`I want to be bathed in starlight`,
`I want to feel like poetry`,
`I want to watch something like Interstellar`,
`I want to feel like I did after Inception`,
`I want to watch a movie that ruins me beautifully`,
`I want to be left speechless by a film`,
`I want to cry at something quiet and slow`,
`I want to watch something that punches me in the gut`,
`I want to be hypnotized by cinematography`,
`I want to get lost in a movie like Spirited Away`,
`I want to feel small like in Gravity`,
`I want a film that makes me question reality`,
`I want to watch something smarter than me`,
`I want a movie that plays like a fever dream`,
`I want to laugh and cry in the same scene`,
`I want to feel haunted after the credits roll`,
`I want to fall in love with the soundtrack`,
`I want to be shocked by a plot twist`,
`I want to watch something like Eternal Sunshine`,
`I want to live inside a Wes Anderson film`,
`I want a cozy movie that feels like home`,
`I want to be wrecked by a quiet indie`,
`I want a movie that messes with time`,
`I want to watch something like Arrival`,
`I want to be enchanted like in Amélie`,
`I want a rom-com that doesn’t feel fake`,
`I want to feel nostalgic for something I’ve never lived`,
`I want to watch something like Oppenheimer`,
`I want to be shaken like after Hereditary`,
`I want a film that’s just vibes`,
`I want to sit in silence after the ending`,
`I want to feel like I’m dreaming`,
`I want to watch something that breaks the fourth wall`,
`I want to watch something so weird it works`,
`I want a movie that feels like a poem`,
`I want to feel heartbroken for fictional people`,
`I want to laugh until I cry`,
`I want to be disturbed but impressed`,
`I want to watch something like The Matrix`,
`I want to watch something like Parasite`,
`I want a movie that feels like a confession`,
`I want to be stunned by beauty`,
`I want to see a world I’ve never imagined`,
`I want to root for someone doomed`,
`I want to be obsessed with the villain`,
`I want to feel the tension in my chest`,
`I want to forget I’m watching a movie`,
`I want a film that whispers secrets`,
`I want to watch something like Whiplash`,
`I want to be emotionally demolished`,
`I want to fall in love with a character`,
`I want a movie that hits like poetry`,
`I want to feel like I’m in space`,
`I want to hear nothing but the score`,
`I want to be confused in a good way`,
`I want to feel clever for figuring it out`,
`I want to be caught off guard`,
`I want a movie that lingers`,
`I want to be comforted by something soft`,
`I want a movie that makes me feel everything`,
`I want a film that doesn’t explain itself`,
`I want to be swallowed by atmosphere`,
`I want to watch something like Blade Runner 2049`,
`I want a movie that gives me chills`,
`I want to feel like I’m inside someone else’s head`,
`I want to forget the real world for two hours`,
`I want a film that teaches me nothing but feels true`,
`I want to watch a movie with no heroes`,
`I want to be devastated and grateful`,
`I want to cry for reasons I don’t understand`,
`I want to sit in the credits and stare`,
`I want a story that’s told with silence`,
`I want to watch something like The Grand Budapest Hotel`,
`I want to time-travel through someone’s life`,
`I want to see love without clichés`,
`I want to feel seen by a movie`,
`I want to laugh at something unexpectedly deep`,
`I want to be shocked by kindness`,
`I want to be unnerved by beauty`,
`I want to be uncomfortable in the best way`,
`I want a film that feels like a secret`,
`I want a movie that feels like a storm`,
`I want to watch something like The Social Network`,
`I want to root for someone morally gray`,
`I want to feel like I’m floating`,
`I want to get chills from a single line`,
`I want to scream “WHAT JUST HAPPENED”`,
`I want to binge-watch pain`,
`I want to sob in the middle of a montage`,
`I want to lose track of time`,
`I want to feel art hit my soul`,
`I want a movie that makes silence loud`,
`I want to watch something like The Lighthouse`,
`I want to feel trapped and thrilled`,
`I want to experience beauty that hurts`,
`I want a movie that’s an emotional maze`,
`I want to fall apart in the best way`,
`I want to question my existence`,
`I want to see joy and grief hold hands`,
`I want to feel like I’ve lived a thousand lives`,
`I want to be ruined with intention`,
`I want to believe in movies again`
]