
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import { configProvider } from '@/config/ConfigProvider';
import type { Database } from './types';

// Get configuration from the strategy
const config = configProvider.getStrategy().getConfig();
const { url, publishableKey } = config.supabase;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(url, publishableKey);

// For debugging
console.log(`Using Supabase environment: ${config.environment}`);
