
name: Deploy Edge Functions

on:
  push:
    branches:
      - main  # Only trigger on main branch pushes
    paths:
      - 'supabase/functions/**'  # Only trigger when functions are modified

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: List modified functions
        id: changed-files
        run: |
          MODIFIED_FUNCTIONS=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep "supabase/functions/" | cut -d'/' -f3 | sort -u)
          echo "Modified functions: $MODIFIED_FUNCTIONS"
          echo "functions=$MODIFIED_FUNCTIONS" >> $GITHUB_OUTPUT

      - name: Set Supabase project variables
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "Using testing environment credentials"
            echo "SUPABASE_PROJECT_ID=${{ secrets.TESTING_PROJECT_ID }}" >> $GITHUB_ENV
            echo "SUPABASE_ACCESS_TOKEN=${{ secrets.TESTING_ACCESS_TOKEN }}" >> $GITHUB_ENV
          else
            echo "Using production environment credentials"
            echo "SUPABASE_PROJECT_ID=${{ secrets.SUPABASE_PROJECT_ID }}" >> $GITHUB_ENV
            echo "SUPABASE_ACCESS_TOKEN=${{ secrets.SUPABASE_ACCESS_TOKEN }}" >> $GITHUB_ENV
          fi

      - name: Deploy modified functions
        run: |
          IFS=' ' read -ra FUNCTIONS <<< "${{ steps.changed-files.outputs.functions }}"
          for function in "${FUNCTIONS[@]}"; do
            if [ ! -z "$function" ]; then
              echo "Deploying function: $function to project: $SUPABASE_PROJECT_ID"
              supabase functions deploy $function --project-ref $SUPABASE_PROJECT_ID --no-verify-jwt --debug
            fi
          done

