
name: Deploy Edge Functions

on:
  push:
    branches:
      - main  # Only trigger on main branch pushes

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: List all functions
        run: |
          FUNCTIONS=$(ls supabase/functions/)
          echo "Functions to deploy: $FUNCTIONS"

      - name: Set Supabase project variables
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "Using testing environment credentials"
            echo "SUPABASE_PROJECT_ID=${{ secrets.TESTING_PROJECT_ID }}" >> $GITHUB_ENV
            echo "SUPABASE_ACCESS_TOKEN=${{ secrets.TESTING_ACCESS_TOKEN }}" >> $GITHUB_ENV
          else
            echo "Using production environment credentials"
            echo "SUPABASE_PROJECT_ID=${{ secrets.SUPABASE_PROJECT_ID }}" >> $GITHUB_ENV
            echo "SUPABASE_ACCESS_TOKEN=${{ secrets.SUPABASE_ACCESS_TOKEN }}" >> $GITHUB_ENV
          fi

      - name: Deploy all functions
        run: |
          for function in $(ls supabase/functions/); do
            echo "Deploying function: $function to project: $SUPABASE_PROJECT_ID"
            supabase functions deploy "$function" --project-ref "$SUPABASE_PROJECT_ID" --no-verify-jwt
          done
