name: Deploy Edge Functions

on:
  push:
    branches:
      - main  # Adjust based on your default branch
    paths:
      - 'supabase/functions/**'  # Trigger on any function change

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Detect changed functions
        id: changed-functions
        run: |
          CHANGED_DIRS=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '^supabase/functions/' | awk -F'/' '{print $3}' | sort -u)
          echo "CHANGED_DIRS=${CHANGED_DIRS}" >> $GITHUB_ENV

      - name: Deploy changed functions
        if: env.CHANGED_DIRS != ''
        run: |
          for function in $CHANGED_DIRS; do
            echo "Deploying function: $function"
            supabase functions deploy $function --project-ref ${{ secrets.SUPABASE_PROJECT_ID }} --no-verify-jwt
          done
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
